strauss: fix off-by-one error in strauss array access
It has to be limited with strauss_lines - 1, not strauss_lines.
Reported by covscan:

    Error: OVERRUN (CWE-119):
    strace-5.18/src/strauss.c:380: cond_at_least: Checking "4UL + i < 37UL"
    implies that "i" is at least 33 on the false branch.
    strace-5.18/src/strauss.c:380: overrun-local: Overrunning array "strauss"
    of 37 8-byte elements at element index 37 (byte offset 303) using index
    "(4UL + i < 37UL) ? 4UL + i : 37UL" (which evaluates to 37).

* src/strauss.c (print_totd): Limit strauss array accesses to
strauss_lines - 1 instead of strauss_lines.